In [3]:
#np.array
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
#2d
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#3d
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#dtype

a = np.array([1,2,3 ],dtype = float)
a
a = np.array([1,2,3],dtype = bool)
a

array([ True,  True,  True])

In [7]:
#arrange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#reshape
np.arange(1,11).reshape(5,2)

np.arange(1,14).reshape(5,2)

ValueError: cannot reshape array of size 13 into shape (5,2)

In [9]:
#np.one and np.zeros
np.ones((2,4),dtype = int)   #bydefault float

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#random
np.random.random((3,4))

array([[0.39473973, 0.64168289, 0.26722594, 0.77227364],
       [0.95418569, 0.63369046, 0.34416007, 0.672509  ],
       [0.85255463, 0.7630709 , 0.36865526, 0.40409854]])

In [12]:
#linspace
np.linspace(-10,10,10)  #first number is lower range ,second number is upper range and third number is no of elements

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
#np.identity
np.identity(4) # create a identity of 4*4


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Array Attributes**

In [14]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3                                          #a1 is vector #a2 is matrix #a3 is tensor

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
#ndim    # gives the dimension of the array

np.ndim(a1)
np.ndim(a2)
np.ndim(a3)



3

In [16]:
#shape     #gives information about rows and columns of the array

a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [17]:
#size
a1.size
a2.size
a3.size


8

In [18]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [19]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


**Changing Datatype**

In [20]:
#astype
a3.dtype       # this is int 64 but to store data of small size we can use int 32
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [21]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
# scaler opeartions
 #arithmetic
a1*2
a1+2
a1**2
a1%2
a1/2   #all will work


array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [23]:
#relational

a2>5
a1>5
a1==15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
#vector operators
# arithmatic

a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

**Arrays Functions**

In [25]:
a1 =  np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[20., 38., 37.],
       [90., 13., 31.],
       [11., 45., 86.]])

In [26]:
#max/min/sum/prod
# np.max(a1)
# np.min(a1)
# np.sum(a1)

# axis-->0 column and axis -->1 rows
np.max(a1 ,axis = 0)



array([90., 45., 86.])

In [27]:
# mean/median/standard deviation/var

np.mean(a1,axis = 1)
np.median(a1,axis = 1)
np.std(a1,axis = 1)
np.var(a1 , axis =1)


array([  68.22222222, 1081.55555556,  940.22222222])

In [28]:
# trignometic functions

np.sin(a1)

array([[ 0.91294525,  0.29636858, -0.64353813],
       [ 0.89399666,  0.42016704, -0.40403765],
       [-0.99999021,  0.85090352, -0.92345845]])

In [29]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [30]:
#log and exponents

np.exp(a1)

array([[4.85165195e+08, 3.18559318e+16, 1.17191424e+16],
       [1.22040329e+39, 4.42413392e+05, 2.90488497e+13],
       [5.98741417e+04, 3.49342711e+19, 2.23524660e+37]])

In [31]:
# round/floor/ceil

np.round(np.random.random((2,3)))*100

array([[100., 100.,   0.],
       [100., 100.,   0.]])

**Indexing and Slicing**

In [6]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
a3[-1]
a3[0]

array([[0, 1],
       [2, 3]])

In [8]:
a2




array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a2[1,3]    # first index denote the number of rows and second index denote the numbers of columns

7

In [10]:
a2[2,3]

11

In [11]:
a2[1,2]

6

In [12]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
a3[1,0,1]      #first index tells in which 2-d array element exists.
               #second index tells in which row element exists .
               # third index tells in which column element exists.

5

In [14]:
a3[1,1,0]

6

In [15]:
a3[0,1,1]

3

In [16]:
a3[0,0,0]

0

In [17]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a1[0:10:2]

array([0, 2, 4, 6, 8])

In [19]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a2[0,:]    # this slicing technique work for rows

array([0, 1, 2, 3])

In [21]:
a2[:,1]

array([1, 5, 9])

In [22]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [23]:
# our target number is 0,3,8,11

a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [24]:
# our target number is 1,3,9,11

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a2[::2,1::2]      #::2 is for row filter 1::2 is for column filter

array([[ 1,  3],
       [ 9, 11]])

In [26]:
#  our target number is  4,7
a2[1:2,0::3]

array([[4, 7]])

In [27]:
# our target number is 1,2,3
                       # 5,6,7
a2[0:2,1::]


array([[1, 2, 3],
       [5, 6, 7]])

In [28]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

**Iterating **

In [29]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [30]:
a2

for i in a2:
  print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
a3
for i in a3:
  print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [32]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


**Reshaping**

In [33]:
#reshape

In [34]:
#Transpose
np.transpose(a2)

a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [35]:
#Ravel      # this function will convert 2-d,3-d array into 1-d array

a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

**Stacking **

In [36]:
# horizontal stacking

a4 = np.arange(12).reshape(3,4)
print(a4)

a5 = np.arange(12,24).reshape(3,4)
print(a5)

np.hstack((a4,a5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [37]:
np.vstack((a4,a5))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Spiliting**

In [39]:
#Horizontal Splitting

np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [41]:
#Vertical Splitting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]